version: '2.2'
services:
services:
  db:
    image: mysql:5.7
    restart: always
    env_file: local.env
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
  
  apache:
    image: httpd:latest
    container_name: my-apache-app
    ports:
    - '8080:80'
    volumes:
    - ./website:/usr/local/apache2/htdocs

  node_app:
    container_name: node_app
    build: 
       context: ./node_app
    restart: always
    ports:
      - "3000:3000"
    env_file: local.env


 
volumes:
  my-db: